# Site settings
title: State CDO Network
email: tyler.kleykamp@georgetown.edu
description: > # this means to ignore newlines until "baseurl:"
  The State Chief Data Officers Netowk.
baseurl: "/Ion-Jekyll-Theme" # the subpath of your site, e.g. /blog/
url: "tkleykamp.github.io/statecdonetwork" # the base hostname & protocol for your site
twitter_username: statecdonetwork
github_username:  tkleykamp

# Build settings
markdown: kramdown
