# Site settings
title: State CDO Network
email: tyler.kleykamp@georgetown.edu
description: > # this means to ignore newlines until "baseurl:"
  The State Chief Data Officers Network. A project hosted by the Beeck Center for Social Impact + Innovation at Georgetown University
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://tkleykamp.github.io/statecdonetwork" # the base hostname & protocol for your site
twitter_username: statecdonetwork
github_username:  tkleykamp

# Build settings
markdown: kramdown
